server:
  port: 8005
spring:
  application:
    name: cloud-commodity-search-consumber

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
  instance:
    prefer-ip-address: true
