server:
  port: 8010
spring:
  application:
    name: orderprovder
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true

  redis:
      host: 127.0.0.1
      port: 6379
      timeout: 20000
  #    集群环境打开下面注释，单机不需要打开
  #    cluster:
  #      集群信息
  #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
  #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
  #      maxRedirects: 3
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
      password:
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meet?useSSL=true&characterEncoding=UTF-8
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6100/eureka/
mybatis:
  mapperLocations: classpath:mapper/*.xml

