server:
  port: 8111
spring:
  application:
    name: cloud-commodity-deatails-consumber
eureka:
  client:
    service-url:
      defaultZone: http://192.168.50.248:6001/eureka/
feign:
  hystrix:
    enabled: true