server:
  port: 8023
spring:
  application:
    name: cloud-commodity-crowdordering-comsumber
eureka:
  client:
    service-url:
      defaultZone: http://39.105.7.229:6001/eureka/
  instance:
    hostname: 39.105.152.84
    prefer-ip-address: true
    instance-id: 39.105.152.84