server:
  port: 8023
spring:
  application:
    name: cloud-commodity-crowdordering-comsumber

eureka:
  client:
    service-url:
      defaultZone: http://39.105.7.229:6001/eureka/
  instance:
    prefer-ip-address: true
