spring:
  application:
    name: cloud-commodity-crowdordering-provlder
  datasource:
    url: jdbc:mysql://39.105.7.229:3306/MettAllcrowdorderingDB?characterEncoding=UTF-8&useSSL=false
    username: root
    password: Sunkefan123..
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: 10000
      max-idle: 8
      min-idle: 0
    timeout: 20000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbit-sun
    password: 123456
    virtual-host: /rabbit-sunkefan
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        default-requeue-rejected: false
eureka:
  client:
    service-url:
      defaultZone: http://39.105.7.229:6001/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8024
mybatis:
  mapperLocations: classpath:mapper/*.xml
