
spring:
  application:
    name: cloud-commodity-crowdordering-provlder
  datasource:
      url: jdbc:mysql://39.105.7.229:3306/MeetAllShopDB?characterEncoding=UTF-8&useSSL=false
      username: root
      password: Sunkefan123..
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: 10000
      max-idle: 8
      min-idle: 0
    timeout: 20000
eureka:
  client:
    service-url:
      defaultZone: http://39.105.7.229:6001/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8024

