#server:
#  port: 8016
#spring:
#  application:
#    name: cloud-commodity-datail-provlder
#  datasource:
#    url: jdbc:mysql://39.105.7.229:3306/MeetAllShopDB?characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: Sunkefan123..
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    druid:
#      initialSize: 5
#      minIdle: 5
#      maxActive: 20
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#  cloud:
#    inetutils:
#      ignored-interfaces[0]: 192.168.50.248
#    config:
#      discovery:
#        enabled: true
#        service-id: meetall-config
#      profile: dev
#      name: cloud-commodity-datail-provlderl
#      label: master
#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.50.248:6001/eureka/
#  instance:
#    hostname: 192.168.50.248
#    instance-id: 192.168.50.248:${server.port}
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
